flattenTheCurve/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts
  resources :tasks

  root to: 'public#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

flattenTheCurve/app/models/task.rb
class Task < ApplicationRecord
end

flattenTheCurve/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_account!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(account_id: current_account)
  end 

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.account_id = current_account.id if account_signed_in?

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :start_time, :end_time, :description, :priority, :completed, :account_id)
    end
end

flattenTheCurve/app/helpers/tasks_helper.rb
module TasksHelper
end

flattenTheCurve/app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="cancel">
  <%= link_to 'Back', tasks_path %>
  </div>
<% end %>

flattenTheCurve/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<div class="form-container">
<%= render 'form', task: @task %>
</div>

flattenTheCurve/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome, user: <%= current_account.email %></h1> 

<%= link_to  "My Account", edit_account_registration_path %>
<%= link_to  "Sign out", edit_account_registration_path, method: :delete %>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Completed</th>
      <th>User</th>
      <th colspan="3">Task Control</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <%# <% if (task.user_id == current_user.id) %>
        <tr>
          <td class="title"><%= task.title %></td>
          <td><%= task.start_time %></td>
          <td class="end-time" data-complete="no" data-title=<%= task.title %>><%= task.end_time %></td>
          <td><%= task.description %></td>
          <td><%= task.priority %></td>
          <td><%= task.completed %></td>
          <td><%= task.account_id %></td>
          <td><%= link_to 'Show', task %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr> 
      <%# <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%# <div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  <strong>Alert!</strong> Indicates a dangerous or potentially negative action.
</div> %>

<%= link_to 'New Task', new_task_path %>

flattenTheCurve/app/views/tasks/new.html.erb
<h1 class="form-heading">New Task</h1>

<div class="form-container">
<%= render 'form', task: @task %>
</div>

flattenTheCurve/app/views/tasks/show.html.erb
<div class="taskshowcontainer">
  
  <h1>Log</h1>

  <div class="taskshow">
  
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @task.title %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= @task.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= @task.end_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= @task.priority %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= @task.completed %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @task.account_id %>
  </p>

  <div class="edit">
  <%= link_to 'Edit', edit_task_path(@task) %> 
  </div>

  <div class="back">
  <%= link_to 'Back', tasks_path %>
</div>
</div>